// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.2
// source: calc/proto/calc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// for request variables
type CalcReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N1 float32 `protobuf:"fixed32,1,opt,name=n1,proto3" json:"n1,omitempty"`
	N2 float32 `protobuf:"fixed32,2,opt,name=n2,proto3" json:"n2,omitempty"`
}

func (x *CalcReq) Reset() {
	*x = CalcReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_proto_calc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CalcReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcReq) ProtoMessage() {}

func (x *CalcReq) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_calc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcReq.ProtoReflect.Descriptor instead.
func (*CalcReq) Descriptor() ([]byte, []int) {
	return file_calc_proto_calc_proto_rawDescGZIP(), []int{0}
}

func (x *CalcReq) GetN1() float32 {
	if x != nil {
		return x.N1
	}
	return 0
}

func (x *CalcReq) GetN2() float32 {
	if x != nil {
		return x.N2
	}
	return 0
}

// for result/response variables
type AddRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R float32 `protobuf:"fixed32,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *AddRes) Reset() {
	*x = AddRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_proto_calc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRes) ProtoMessage() {}

func (x *AddRes) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_calc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRes.ProtoReflect.Descriptor instead.
func (*AddRes) Descriptor() ([]byte, []int) {
	return file_calc_proto_calc_proto_rawDescGZIP(), []int{1}
}

func (x *AddRes) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

type SubRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R float32 `protobuf:"fixed32,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *SubRes) Reset() {
	*x = SubRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_proto_calc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRes) ProtoMessage() {}

func (x *SubRes) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_calc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRes.ProtoReflect.Descriptor instead.
func (*SubRes) Descriptor() ([]byte, []int) {
	return file_calc_proto_calc_proto_rawDescGZIP(), []int{2}
}

func (x *SubRes) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

type DivRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R float32 `protobuf:"fixed32,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *DivRes) Reset() {
	*x = DivRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_proto_calc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DivRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivRes) ProtoMessage() {}

func (x *DivRes) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_calc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivRes.ProtoReflect.Descriptor instead.
func (*DivRes) Descriptor() ([]byte, []int) {
	return file_calc_proto_calc_proto_rawDescGZIP(), []int{3}
}

func (x *DivRes) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

type MulRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	R float32 `protobuf:"fixed32,1,opt,name=r,proto3" json:"r,omitempty"`
}

func (x *MulRes) Reset() {
	*x = MulRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_calc_proto_calc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MulRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MulRes) ProtoMessage() {}

func (x *MulRes) ProtoReflect() protoreflect.Message {
	mi := &file_calc_proto_calc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MulRes.ProtoReflect.Descriptor instead.
func (*MulRes) Descriptor() ([]byte, []int) {
	return file_calc_proto_calc_proto_rawDescGZIP(), []int{4}
}

func (x *MulRes) GetR() float32 {
	if x != nil {
		return x.R
	}
	return 0
}

var File_calc_proto_calc_proto protoreflect.FileDescriptor

var file_calc_proto_calc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x07, 0x43, 0x61, 0x6c, 0x63, 0x52,
	0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02,
	0x6e, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x6e, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x02,
	0x6e, 0x32, 0x22, 0x16, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x72, 0x22, 0x16, 0x0a, 0x06, 0x53, 0x75,
	0x62, 0x52, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x72, 0x22, 0x16, 0x0a, 0x06, 0x44, 0x69, 0x76, 0x52, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x72, 0x22, 0x16, 0x0a, 0x06, 0x4d, 0x75,
	0x6c, 0x52, 0x65, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x01, 0x72, 0x32, 0x7c, 0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x1a, 0x0a, 0x03, 0x41, 0x64, 0x64, 0x12, 0x08, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65,
	0x71, 0x1a, 0x07, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x1a, 0x0a, 0x03,
	0x53, 0x75, 0x62, 0x12, 0x08, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x07, 0x2e,
	0x53, 0x75, 0x62, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x1a, 0x0a, 0x03, 0x44, 0x69, 0x76, 0x12,
	0x08, 0x2e, 0x43, 0x61, 0x6c, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x07, 0x2e, 0x44, 0x69, 0x76, 0x52,
	0x65, 0x73, 0x22, 0x00, 0x12, 0x1a, 0x0a, 0x03, 0x4d, 0x75, 0x6c, 0x12, 0x08, 0x2e, 0x43, 0x61,
	0x6c, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x07, 0x2e, 0x4d, 0x75, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x42, 0x0c, 0x5a, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_calc_proto_calc_proto_rawDescOnce sync.Once
	file_calc_proto_calc_proto_rawDescData = file_calc_proto_calc_proto_rawDesc
)

func file_calc_proto_calc_proto_rawDescGZIP() []byte {
	file_calc_proto_calc_proto_rawDescOnce.Do(func() {
		file_calc_proto_calc_proto_rawDescData = protoimpl.X.CompressGZIP(file_calc_proto_calc_proto_rawDescData)
	})
	return file_calc_proto_calc_proto_rawDescData
}

var file_calc_proto_calc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_calc_proto_calc_proto_goTypes = []interface{}{
	(*CalcReq)(nil), // 0: CalcReq
	(*AddRes)(nil),  // 1: AddRes
	(*SubRes)(nil),  // 2: SubRes
	(*DivRes)(nil),  // 3: DivRes
	(*MulRes)(nil),  // 4: MulRes
}
var file_calc_proto_calc_proto_depIdxs = []int32{
	0, // 0: Calculator.Add:input_type -> CalcReq
	0, // 1: Calculator.Sub:input_type -> CalcReq
	0, // 2: Calculator.Div:input_type -> CalcReq
	0, // 3: Calculator.Mul:input_type -> CalcReq
	1, // 4: Calculator.Add:output_type -> AddRes
	2, // 5: Calculator.Sub:output_type -> SubRes
	3, // 6: Calculator.Div:output_type -> DivRes
	4, // 7: Calculator.Mul:output_type -> MulRes
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calc_proto_calc_proto_init() }
func file_calc_proto_calc_proto_init() {
	if File_calc_proto_calc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_calc_proto_calc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CalcReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calc_proto_calc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calc_proto_calc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calc_proto_calc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DivRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_calc_proto_calc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MulRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_calc_proto_calc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calc_proto_calc_proto_goTypes,
		DependencyIndexes: file_calc_proto_calc_proto_depIdxs,
		MessageInfos:      file_calc_proto_calc_proto_msgTypes,
	}.Build()
	File_calc_proto_calc_proto = out.File
	file_calc_proto_calc_proto_rawDesc = nil
	file_calc_proto_calc_proto_goTypes = nil
	file_calc_proto_calc_proto_depIdxs = nil
}
